apiVersion: 1

datasources:
  - name: SIGES PostgreSQL
    uid: siges-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: siges
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      database: siges_cctv
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
