CREATE TYPE "Permission" AS ENUM (
  'MANAGE_USERS',
  'MANAGE_ORG',
  'MANAGE_ROUTES',
  'MANAGE_NODES',
  'MANAGE_FIBER',
  'MANAGE_CAMERAS',
  'CAMERA_PREVIEW',
  'RUN_DISCOVERY',
  'RESOLVE_DISCOVERY',
  'VIEW_TELEMETRY'
);

ALTER TABLE "User"
ADD COLUMN "permissions" "Permission"[] NOT NULL DEFAULT ARRAY[]::"Permission"[];
